import type { Client, Worker, Job, Invoice, Expense } from '@/types/database'

export const ROLES = {
  owner: { label: 'Owner', emoji: '👑', color: '#2D6A4F', desc: 'Full access to all data and settings' },
  worker: { label: 'Crew', emoji: '🚛', color: '#3B82F6', desc: 'My jobs, time tracking, routes only' },
  client: { label: 'Client', emoji: '🏡', color: '#8B5CF6', desc: 'My appointments and invoices only' },
}

export const COLORS = {
  primary: '#2D6A4F',
  light: '#52B788',
  success: '#22C55E',
  warning: '#F59E0B',
  error: '#EF4444',
  info: '#3B82F6',
}

export const DEMO_WORKERS: Worker[] = [
  {
    id: 'w1',
    business_id: '',
    name: 'Meleah McKnight',
    role: 'Crew Lead',
    phone: '(206)111-2222',
    color: '#2D6A4F',
    hours_today: 4.5,
    hours_week: 32,
    pay_rate: 28,
    tax_type: 'W-2',
    ssn: '***-**-4521',
    ytd_wages: 44800,
    status: 'active',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'w2',
    business_id: '',
    name: 'Jake T.',
    role: 'Laborer',
    phone: '(206)222-3333',
    color: '#3B82F6',
    hours_today: 3.2,
    hours_week: 28,
    pay_rate: 22,
    tax_type: 'W-2',
    ssn: '***-**-7732',
    ytd_wages: 28160,
    status: 'active',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'w3',
    business_id: '',
    name: 'Maria L.',
    role: 'Laborer',
    phone: '(206)333-4444',
    color: '#8B5CF6',
    hours_today: 2.8,
    hours_week: 21,
    pay_rate: 22,
    tax_type: 'W-2',
    ssn: '***-**-9901',
    ytd_wages: 24024,
    status: 'break',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'w4',
    business_id: '',
    name: 'Diego R.',
    role: 'Driver',
    phone: '(206)444-5555',
    color: '#F97316',
    hours_today: 0,
    hours_week: 14,
    pay_rate: 20,
    tax_type: '1099',
    ein: '92-3841209',
    ytd_wages: 14560,
    status: 'idle',
    created_at: '',
    updated_at: '',
  },
]

export const DEMO_CLIENTS: Client[] = [
  {
    id: '1',
    business_id: '',
    name: 'Margaret Chen',
    phone: '(206)234-5678',
    email: 'm.chen@email.com',
    address: '142 Oakwood Dr, Renton WA',
    status: 'active',
    ltv: 4850,
    balance: 0,
    next_job: 'Feb 24',
    since: 'Mar 2023',
    notes: 'Gate 4521. Friendly dog Max.',
    sensitive_notes: 'Excellent payer. Consider upselling drainage work.',
    created_at: '',
    updated_at: '',
  },
  {
    id: '2',
    business_id: '',
    name: 'Robert Alvarez',
    phone: '(206)345-6789',
    email: 'ralvarez@biz.com',
    address: '88 Pecan Ave, Bellevue WA',
    status: 'active',
    ltv: 2200,
    balance: 308,
    next_job: 'Feb 22',
    since: 'Aug 2024',
    notes: 'Invoice by email only.',
    sensitive_notes: 'Slow payer — always 10-14 days. Consider deposits.',
    created_at: '',
    updated_at: '',
  },
  {
    id: '3',
    business_id: '',
    name: 'Susan & Tom Park',
    phone: '(206)456-7890',
    email: 'park@mail.com',
    address: '2201 Willow Ln, Kirkland WA',
    status: 'active',
    ltv: 7100,
    balance: 0,
    next_job: 'Feb 26',
    since: 'Jan 2022',
    notes: 'Seasonal cleanup quarterly.',
    sensitive_notes: 'Best client. Target for annual contract pitch.',
    created_at: '',
    updated_at: '',
  },
  {
    id: '4',
    business_id: '',
    name: 'Lighthouse Café',
    phone: '(206)567-8901',
    email: 'cafe@light.com',
    address: '510 Rainier Ave S, Seattle WA',
    status: 'overdue',
    ltv: 5600,
    balance: 875,
    next_job: 'Mar 1',
    since: 'Jun 2023',
    notes: 'Commercial. 2 locations.',
    sensitive_notes: 'OVERDUE. Consider pausing service until paid.',
    created_at: '',
    updated_at: '',
  },
  {
    id: '5',
    business_id: '',
    name: 'David Kim',
    phone: '(206)678-9012',
    email: 'dkim@gmail.com',
    address: '3301 Sunset Ridge Rd, Issaquah WA',
    status: 'active',
    ltv: 1400,
    balance: 0,
    next_job: 'Feb 28',
    since: 'Nov 2024',
    notes: 'Wants redesign quote.',
    sensitive_notes: 'Low LTV but high potential. Nurture.',
    created_at: '',
    updated_at: '',
  },
]

export const DEMO_JOBS: Job[] = [
  {
    id: '1',
    business_id: '',
    client_id: '1',
    type: 'Lawn Mowing',
    address: '142 Oakwood Dr, Renton WA',
    lat: 47.48,
    lng: -122.213,
    status: 'in-progress',
    scheduled_date: 'Today',
    scheduled_time: '8:00 AM',
    price: 120,
    notes: 'Gate code 4521. Dog inside.',
    sensitive_notes: 'Client owes $0. Excellent payer. Upsell irrigation check.',
    created_at: '',
    updated_at: '',
  },
  {
    id: '2',
    business_id: '',
    client_id: '2',
    type: 'Mulching',
    address: '88 Pecan Ave, Bellevue WA',
    lat: 47.612,
    lng: -122.201,
    status: 'scheduled',
    scheduled_date: 'Today',
    scheduled_time: '11:00 AM',
    price: 285,
    notes: '4 cu yards cedar mulch. Front beds only.',
    sensitive_notes: 'Net 7 terms. Has outstanding invoice INV-0090 $308.',
    created_at: '',
    updated_at: '',
  },
  {
    id: '3',
    business_id: '',
    client_id: '4',
    type: 'Cleanup',
    address: '510 Rainier Ave S, Seattle WA',
    lat: 47.566,
    lng: -122.303,
    status: 'completed',
    scheduled_date: 'Today',
    scheduled_time: '7:00 AM',
    price: 95,
    notes: 'Early morning. Patio priority.',
    sensitive_notes: 'OVERDUE — 9 days past due $184.81. Firm reminder sent.',
    created_at: '',
    updated_at: '',
  },
  {
    id: '4',
    business_id: '',
    client_id: '3',
    type: 'Seasonal Cleanup',
    address: '2201 Willow Ln, Kirkland WA',
    lat: 47.682,
    lng: -122.207,
    status: 'scheduled',
    scheduled_date: 'Feb 21',
    scheduled_time: '9:00 AM',
    price: 650,
    notes: 'Full spring cleanup. Very particular about edging.',
    sensitive_notes: 'Top client LTV $7,100. Offer spring maintenance contract.',
    created_at: '',
    updated_at: '',
  },
  {
    id: '5',
    business_id: '',
    client_id: '5',
    type: 'Lawn Mowing',
    address: '3301 Sunset Ridge Rd, Issaquah WA',
    lat: 47.53,
    lng: -122.033,
    status: 'scheduled',
    scheduled_date: 'Feb 28',
    scheduled_time: '10:00 AM',
    price: 110,
    notes: 'Steep backyard — use push mower.',
    sensitive_notes: 'Interested in redesign. Potential $2k+ project.',
    created_at: '',
    updated_at: '',
  },
  {
    id: '6',
    business_id: '',
    client_id: '1',
    type: 'Irrigation',
    address: '800 Pine Valley Blvd, Mercer Island WA',
    lat: 47.571,
    lng: -122.221,
    status: 'scheduled',
    scheduled_date: 'Today',
    scheduled_time: '1:00 PM',
    price: 180,
    notes: 'Check all 12 zones.',
    sensitive_notes: 'Commercial account. Invoice monthly Net 30.',
    created_at: '',
    updated_at: '',
  },
]

export const DEMO_INVOICES: Invoice[] = [
  { id: '1', business_id: '', client_id: '3', invoice_number: 'INV-0091', amount: 717.14, status: 'unpaid', issue_date: '2026-02-19', due_date: '2026-02-26', paid_at: null, payment_method: null, created_at: '', updated_at: '' },
  { id: '2', business_id: '', client_id: '2', invoice_number: 'INV-0090', amount: 308.49, status: 'unpaid', issue_date: '2026-02-19', due_date: '2026-02-26', paid_at: null, payment_method: null, created_at: '', updated_at: '' },
  { id: '3', business_id: '', client_id: '4', invoice_number: 'INV-0089', amount: 184.81, status: 'overdue', issue_date: '2026-02-05', due_date: '2026-02-12', paid_at: null, payment_method: null, created_at: '', updated_at: '' },
  { id: '4', business_id: '', client_id: '1', invoice_number: 'INV-0088', amount: 130.23, status: 'paid', issue_date: '2026-02-05', due_date: '2026-02-12', paid_at: '2026-02-10', payment_method: 'Venmo', created_at: '', updated_at: '' },
  { id: '5', business_id: '', client_id: '5', invoice_number: 'INV-0087', amount: 119.82, status: 'paid', issue_date: '2026-01-22', due_date: '2026-01-29', paid_at: '2026-01-28', payment_method: 'Check', created_at: '', updated_at: '' },
]

export const DEMO_EXPENSES: Expense[] = [
  { id: '1', business_id: '', date: '2026-02-19', category: 'Fuel', amount: 87.4, description: 'Gas — 2 trucks', deductible: true, created_at: '', updated_at: '' },
  { id: '2', business_id: '', date: '2026-02-18', category: 'Supplies', amount: 312.0, description: 'Cedar mulch', deductible: true, created_at: '', updated_at: '' },
  { id: '3', business_id: '', date: '2026-02-17', category: 'Equipment', amount: 189.99, description: 'Mower blade', deductible: true, created_at: '', updated_at: '' },
  { id: '4', business_id: '', date: '2026-02-15', category: 'Fuel', amount: 65.0, description: 'Gas — mower', deductible: true, created_at: '', updated_at: '' },
  { id: '5', business_id: '', date: '2026-02-14', category: 'Equipment', amount: 45.5, description: 'String trimmer line', deductible: true, created_at: '', updated_at: '' },
]
